### ISSUE TITLE
Fix npm vulnerabilities for frontend

### ISSUE THREAD

**Issue by Ananto30** [Ananto30/ask-hadith#36]
Currently npm install shows this - `found 48 vulnerabilities (29 moderate, 18 high, 1 critical)` for frontend.
Need to fix that.

**Comment by aayushbisen** [comment]
Can I work on this issue?

**Comment by Ananto30** [comment]
Sure go on! 🚀

**Comment by aayushbisen** [comment]
Hi, I tried running `npm audit fix` but it is not resolving the vulnerabilities.

I guess the issue is with react package. I also tried giving the `--force` flag but the vulnerabilities are still there.

**Comment by Ananto30** [comment]
Maybe. I tried them too but didn't work. I'm not an expert in npm, so can't tell 😅

**Comment by Ananto30** [comment]
Closing as this is solved
